export const DELTA_POST_POPULAR_COURSES = 'DELTA_POST_POPULAR_COURSES';
export const DELTA_POST_POPULAR_ELEMENTS = 'DELTA_POST_POPULAR_ELEMENTS';

export const DELTA_MOST_POPULAR_TODAY = 'TODAY';
export const DELTA_MOST_POPULAR_WEEK = 'WEEK';
export const DELTA_MOST_POPULAR_MONTH = 'MONTH';
export const DELTA_MOST_POPULAR_YEAR = 'YEAR';
export const DELTA_MOST_POPULAR_ALL = 'ALL';