export const ADMIN_EDIT_FILE_FETCH_STARTED = 'ADMIN_EDIT_FILE_FETCH_STARTED';
export const ADMIN_EDIT_FILE_FETCH_FINISHED = 'ADMIN_EDIT_FILE_FETCH_FINISHED';
export const ADMIN_EDIT_FILE_FETCH_FAILED = 'ADMIN_EDIT_FILE_FETCH_FAILED';

export const ADMIN_EDIT_FILE_PUT_STARTED = 'ADMIN_EDIT_FILE_PUT_STARTED';
export const ADMIN_EDIT_FILE_PUT_FINISHED = 'ADMIN_EDIT_FILE_PUT_FINISHED';
export const ADMIN_EDIT_FILE_PUT_FAILED = 'ADMIN_EDIT_FILE_PUT_FAILED';

export const ADMIN_EDIT_FILE_SHOW_MODAL = 'ADMIN_EDIT_FILE_SHOW_MODAL';
export const ADMIN_EDIT_FILE_HIDE_MODAL = 'ADMIN_EDIT_FILE_HIDE_MODAL';

export const ADMIN_EDIT_FILE_TOGGLE_CHECKBOX = 'ADMIN_EDIT_FILE_TOGGLE_CHECKBOX';
export const ADMIN_EDIT_FILE_CHANGE_PARENT = 'ADMIN_EDIT_FILE_CHANGE_PARENT';
export const ADMIN_EDIT_FILE_CHANGE_VALUE = 'ADMIN_EDIT_FILE_CHANGE_VALUE';
