export const ADMIN_EDIT_FILE_FETCH_STARTED = 'ADMIN_EDIT_FILE_FETCH_STARTED';
export const ADMIN_EDIT_FILE_FETCH_FINISHED = 'ADMIN_EDIT_FILE_FETCH_FINISHED';
export const ADMIN_EDIT_FILE_FETCH_FAILED = 'ADMIN_EDIT_FILE_FETCH_FAILED';

export const ADMIN_EDIT_FILE_POST_STARTED = 'ADMIN_EDIT_FILE_POST_STARTED';
export const ADMIN_EDIT_FILE_POST_FINISHED = 'ADMIN_EDIT_FILE_POST_FINISHED';
export const ADMIN_EDIT_FILE_POST_FAILED = 'ADMIN_EDIT_FILE_POST_FAILED';

export const ADMIN_EDIT_FILE_SHOW_MODAL = 'ADMIN_EDIT_FILE_SHOW_MODAL';
export const ADMIN_EDIT_FILE_HIDE_MODAL = 'ADMIN_EDIT_FILE_HIDE_MODAL';
