export const FRONTPAGE_BOXES_FETCH_STARTED = 'FRONTPAGE_BOXES_FETCH_STARTED';
export const FRONTPAGE_BOXES_FETCH_FINISHED = 'FRONTPAGE_BOXES_FETCH_FINISHED';
export const FRONTPAGE_BOXES_FETCH_FAILED = 'FRONTPAGE_BOXES_FETCH_FAILED';
