language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

notifications:
  email: false

install:
  composer install --no-interaction

before_script:
  - cp _scripts/src/install-phinx phinx.yml
  - cp _scripts/src/install-local-empty local.php

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php composer.phar phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then php composer.phar phpunit ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php composer.phar phpcs ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php composer.phar phpmd ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php composer.phar coveralls --coverage_clover=clover.xml -v ; fi
