sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  # Install dependencies, only install testing stuff for 5.6
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:1.* squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

before_script:
  # Deploy phinx file
  - cp _scripts/src/install-phinx phinx.yml
  
  # Deploy mpty local.php file
  - cp _scripts/src/install-local-empty local.php

script:
  # Run the tests
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then phpunit ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpcs ; fi

after_script:
  # If we are currently testing 5.6, also execute coveralls
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi
