language: php
php:
  - '7.3.5'

notifications:
  email: false

before_install:
  - cd youkok2
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mkdir build/logs

install:
  composer install --no-interaction

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - ./vendor/bin/coveralls --coverage_clover=clover.xml -v
