language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2

notifications:
  email: false

install:
  composer install --no-interaction

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then composer phpcs ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then composer phpmd ./src text phpmd; fi
#  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php composer.phar phpunit --coverage-clover clover.xml ; fi
#  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then php composer.phar phpunit ; fi

#after_script:
#  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php composer.phar coveralls --coverage_clover=clover.xml -v ; fi
