language: php
php:
  - '7.3.5'

notifications:
  email: false

before_install: cd youkok2

install:
  composer install --no-interaction

script:
  - composer phpcs
  - php composer.phar phpunit --coverage-clover clover.xml
  - php composer.phar phpunit

after_script:
  - php composer.phar coveralls --coverage_clover=clover.xml -v
