version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    restart: always
    env_file:
      - prod.env

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    restart: always

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./docker/logs:/var/log/youkok2
      - ./youkok2:/var/www/html
      - ./docker/files:/var/www/files
      - ./docker/cache:/var/www/cache
    build:
      args:
        - YOUKOK_ENV=prod
