version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    restart: always
    env_file:
      - prod.env

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    restart: always

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    restart: always
    env_file:
      - prod.env
    build:
      args:
        - WITH_XDEBUG=false
