version: '2'

services:

  ###############################################
  #                    Files                    #
  ###############################################

  appdata:
    container_name: "youkok2_files"
    image: "alpine:3.5"
    command: tail -f /dev/null
    user: "1000"
    network_mode: "none"
    volumes:
      - .:/var/www/html
      - ./youkok_files:/var/www/files


  ###############################################
  #                   Database                  #
  ###############################################

  db:
    container_name: "youkok2_db"
    image: "mysql:5.7.17"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=youkok2
      - MYSQL_PASSWORD=youkok2
      - MYSQL_DATABASE=youkok2
    volumes:
      - /var/lib/mysql


  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    container_name: "youkok2_cache"
    image: "redis:4.0.2-alpine"
    ports:
     - "6379:6379"
    volumes:
      - /data


  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    container_name: "youkok2_web"
    depends_on:
      - db
      - appdata
      - cache
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:80"
    environment:
      - docker=1
      - COMPOSER_ALLOW_SUPERUSER=1
      - MYSQL_USER=youkok2
      - MYSQL_PASSWORD=youkok2
      - MYSQL_DATABASE=youkok2
    links:
      - db
      - cache
    volumes_from:
      - appdata