version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    container_name: "youkok2_db"
    image: "mysql:5.7.17"
    ports:
      - "3316:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=youkok2
    - MYSQL_PASSWORD=youkok2
    - MYSQL_DATABASE=youkok2
    volumes:
      - /var/lib/mysql

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    container_name: "youkok2_cache"
    image: "redis:4.0.2-alpine"
    ports:
     - "6389:6379"
    volumes:
      - /data

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    container_name: "youkok2_web"
    depends_on:
      - db
      - cache
    user: "0"
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:80"
    volumes:
      - ./docker/logs:/var/log/youkok2
      - ./youkok2:/var/www/html
      - ./docker/files:/var/www/files
      - ./docker/cache:/var/www/cache
    links:
      - db
      - cache