version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  youkok2-db:
    build:
      context: .
      dockerfile: docker_db.Dockerfile
    container_name: "youkok2_db_dev"
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - env_db_dev.env

  ###############################################
  #                    Cache                    #
  ###############################################

  youkok2-cache:
    image: "redis:6.0.8-alpine"
    container_name: "youkok2_cache_dev"
    ports:
      - "6379:6379"

  ###############################################
  #                  Webserver                  #
  ###############################################

  youkok2-php:
    build:
      context: .
      dockerfile: docker_php.Dockerfile
      args:
        - ENV=dev
    container_name: "youkok2_php_dev"
    ports:
      - "9000"
    env_file:
      - env_php_dev.env
    volumes:
      - ./youkok2:/code/site
      - ./_docker/files:/code/files
    depends_on:
      - youkok2-db
      - youkok2-cache
    links:
      - youkok2-db
      - youkok2-cache

  ###############################################
  #                    Nginx                    #
  ###############################################

  youkok2-nginx:
    build:
      context: .
      dockerfile: docker_nginx.Dockerfile
    container_name: "youkok2_nginx_dev"
    ports:
      - "8091:80"
    volumes:
      - ./_docker/site.conf:/etc/nginx/conf.d/site.conf
      - ./static:/static
    depends_on:
      - youkok2-php
    links:
      - youkok2-php

  ###############################################
  #                 Migrations                  #
  ###############################################

  youkok2-migrations:
    build:
      context: .
      dockerfile: docker_migrations.Dockerfile
      args:
        - ENV=dev
    container_name: "youkok2_migrations_dev"
    environment:
      WAIT_HOSTS: youkok2-db:3306
    env_file:
      - env_php_dev.env
    volumes:
      - ./youkok2:/code/site
    depends_on:
      - youkok2-db
    links:
      - youkok2-db

