version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    image: "mysql:5.7.17"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    image: "redis:4.0.14-alpine"
    volumes:
      - /data

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    depends_on:
      - db
      - cache
    user: "0"
    env_file: dev.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    links:
      - db
      - cache
