version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - /var/lib/mysql

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    image: "redis:4.0.14-alpine"
    volumes:
      - /data

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    depends_on:
      - db
      - cache
    user: "0"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    links:
      - db
      - cache
