version: '2'

services:

  ###############################################
  #                   Database                  #
  ###############################################

  db:
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root_password
    - MYSQL_USER=mysql_user
    - MYSQL_PASSWORD=mysql_password
    - MYSQL_DATABASE=mysql_database

  ###############################################
  #                    Cache                    #
  ###############################################

  cache:
    restart: always

  ###############################################
  #                  Webserver                  #
  ###############################################

  server:
    restart: always