export const ADMIN_HOME_BOXES_FETCH_STARTED = 'ADMIN_HOME_BOXES_FETCH_STARTED';
export const ADMIN_HOME_BOXES_FETCH_FINISHED = 'ADMIN_HOME_BOXES_FETCH_FINISHED';
export const ADMIN_HOME_BOXES_FETCH_FAILED = 'ADMIN_HOME_BOXES_FETCH_FAILED';
