export const ADMIN_HOME_GRAPH_FETCH_STARTED = 'ADMIN_HOME_GRAPH_FETCH_STARTED';
export const ADMIN_HOME_GRAPH_FETCH_FINISHED = 'ADMIN_HOME_GRAPH_FETCH_FINISHED';
export const ADMIN_HOME_GRAPH_FETCH_FAILED = 'ADMIN_HOME_GRAPH_FETCH_FAILED';
