export const SIDEBAR_MOST_POPULAR_FETCH_STARTED = 'SIDEBAR_MOST_POPULAR_FETCH_STARTED';
export const SIDEBAR_MOST_POPULAR_FETCH_FINISHED = 'SIDEBAR_MOST_POPULAR_FETCH_FINISHED';
export const SIDEBAR_MOST_POPULAR_FETCH_FAILED = 'SIDEBAR_MOST_POPULAR_FETCH_FAILED';
