export const SIDEBAR_HISTORY_FETCH_STARTED = 'SIDEBAR_HISTORY_FETCH_STARTED';
export const SIDEBAR_HISTORY_FETCH_FINISHED = 'SIDEBAR_HISTORY_FETCH_FINISHED';
export const SIDEBAR_HISTORY_FETCH_FAILED = 'SIDEBAR_HISTORY_FETCH_FAILED';
