export const FRONTPAGE_FETCH_STARTED = 'FRONTPAGE_FETCH_STARTED';
export const FRONTPAGE_FETCH_FINISHED = 'FRONTPAGE_FETCH_FINISHED';
export const FRONTPAGE_FETCH_FAILED = 'FRONTPAGE_FETCH_FAILED';

export const FRONTPAGE_DELTA_CHANGE_STARTED = 'FRONTPAGE_DELTA_CHANGE_STARTED';
export const FRONTPAGE_DELTA_CHANGE_FINISHED = 'FRONTPAGE_DELTA_CHANGE_FINISHED';
export const FRONTPAGE_DELTA_CHANGE_FAILED = 'FRONTPAGE_DELTA_CHANGE_FAILED';