export const SIDEBAR_POST_LINK_CHANGE = 'SIDEBAR_POST_LINK_CHANGE';
export const SIDEBAR_POST_LINK_RESET = 'SIDEBAR_POST_LINK_RESET';
export const SIDEBAR_POST_LINK_TITLE_CHANGE = 'SIDEBAR_POST_LINK_TITLE_CHANGE';

export const SIDEBAR_POST_LINK_TITLE_FETCH_STARTED = 'SIDEBAR_POST_LINK_TITLE_FETCH_STARTED';
export const SIDEBAR_POST_LINK_TITLE_FETCH_FINISHED = 'SIDEBAR_POST_LINK_TITLE_FETCH_FINISHED';
export const SIDEBAR_POST_LINK_TITLE_FETCH_FAILED = 'SIDEBAR_POST_LINK_TITLE_FETCH_FAILED';

export const SIDEBAR_POST_LINK_TITLE_POST_ERROR = 'SIDEBAR_POST_LINK_TITLE_POST_ERROR';

export const SIDEBAR_POST_LINK_TITLE_POST_STARTED = 'SIDEBAR_POST_LINK_TITLE_POST_STARTED';
export const SIDEBAR_POST_LINK_TITLE_POST_FINISHED = 'SIDEBAR_POST_LINK_TITLE_POST_FINISHED';
export const SIDEBAR_POST_LINK_TITLE_POST_FAILED = 'SIDEBAR_POST_LINK_TITLE_POST_FAILED';
