export const ADMIN_FILES_FETCH_STARTED = 'ADMIN_FILES_FETCH_STARTED';
export const ADMIN_FILES_FETCH_FINISHED = 'ADMIN_FILES_FETCH_FINISHED';
export const ADMIN_FILES_FETCH_FAILED = 'ADMIN_FILES_FETCH_FAILED';
