export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_CURSOR_POSITION = 'UPDATE_CURSOR_POSITION';

export const CLOSE_SEARCH_RESULTS = 'CLOSE_SEARCH_RESULTS';