export const ADMIN_CREATE_DIRECTORY_POST_STARTED = 'ADMIN_CREATE_DIRECTORY_POST_STARTED';
export const ADMIN_CREATE_DIRECTORY_POST_FINISHED = 'ADMIN_CREATE_DIRECTORY_POST_FINISHED';
export const ADMIN_CREATE_DIRECTORY_POST_FAILED = 'ADMIN_CREATE_DIRECTORY_POST_FAILED';

export const ADMIN_CREATE_DIRECTORY_SHOW_MODAL = 'ADMIN_CREATE_DIRECTORY_SHOW_MODAL';
export const ADMIN_CREATE_DIRECTORY_HIDE_MODAL = 'ADMIN_CREATE_DIRECTORY_HIDE_MODAL';

export const ADMIN_CREATE_DIRECTORY_UPDATE_VALUE = 'ADMIN_CREATE_DIRECTORY_UPDATE_VALUE';
