paths:
    migrations: %%PHINX_CONFIG_DIR%%/../migrations

environments:
    default_migration_table: phinxlog
    default_database: production
    production:
        adapter: mysql
        host: db
        name: youkok2
        user: youkok2
        pass: 'youkok2'
        port: 3306
        charset: utf8
    test:
        adapter: sqlite
        name: ./tests/files/db.sqlite3
