export const COURSES_CHANGE_ORDER = 'COURSES_CHANGE_ORDER';
export const COURSES_CHANGE_PAGE = 'COURSES_CHANGE_PAGE';
export const COURSES_UPDATE_SEARCH = 'COURSES_UPDATE_SEARCH';
export const COURSE_CHANGE_CHECKBOX = 'COURSE_CHANGE_CHECKBOX';
