export const FRONTPAGE_NEWEST_FETCH_STARTED = 'FRONTPAGE_NEWEST_FETCH_STARTED';
export const FRONTPAGE_NEWEST_FETCH_FINISHED = 'FRONTPAGE_NEWEST_FETCH_FINISHED';
export const FRONTPAGE_NEWEST_FETCH_FAILED = 'FRONTPAGE_NEWEST_FETCH_FAILED';
