export const DELTA_POST_POPULAR_COURSES = 'most_popular_course';
export const DELTA_POST_POPULAR_ELEMENTS = 'most_popular_element';

export const DELTA_MOST_POPULAR_TODAY = 'DAY';
export const DELTA_MOST_POPULAR_WEEK = 'WEEK';
export const DELTA_MOST_POPULAR_MONTH = 'MONTH';
export const DELTA_MOST_POPULAR_YEAR = 'YEAR';
export const DELTA_MOST_POPULAR_ALL = 'ALL';

export const DEFAULT_MOST_POPULAR_ELEMENTS_DELTA = DELTA_MOST_POPULAR_MONTH;
export const DEFAULT_MOST_POPULAR_COURSES_DELTA = DELTA_MOST_POPULAR_MONTH;
