export const ADMIN_FILES_PENDING_FETCH_STARTED = 'ADMIN_FILES_PENDING_FETCH_STARTED';
export const ADMIN_FILES_PENDING_FETCH_FINISHED = 'ADMIN_FILES_PENDING_FETCH_FINISHED';
export const ADMIN_FILES_PENDING_FETCH_FAILED = 'ADMIN_FILES_PENDING_FETCH_FAILED';
