#!/bin/sh
set -e

# Start the cronjob
/etc/init.d/cron start

# Copied from https://github.com/docker-library/php
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
